const input = [
	{
		id: "E1",
		name: "gita",
		gender: "female",
		Location: "bkc",
		role: "SSA2",
		wantCompoff: "no",
		availableForNight: "no",
		interestedForContinousCompoff: "no",
		group: "G1",
	},
	{
		id: "E3",
		name: "janhvi",
		gender: "female",
		Location: "bkc",
		role: "SA1",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G1",
	},
	{
		id: "E4",
		name: "christina",
		gender: "female",
		Location: "bkc",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G1",
	},
	{
		id: "E2",
		name: "savitha",
		gender: "female",
		Location: "bcp",
		role: "SSA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G1",
	},
	{
		id: "E9",
		name: "sarvesh",
		gender: "male",
		Location: "bkc",
		role: "LEAD1",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E10",
		name: "prabhakr",
		gender: "male",
		Location: "bcp",
		role: "LEAD2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E11",
		name: "balachander",
		gender: "male",
		Location: "bcp",
		role: "LEAD3",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E12",
		name: "santosh",
		gender: "male",
		Location: "bkc",
		role: "SSA1",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E13",
		name: "shubhamKadam",
		gender: "male",
		Location: "bkc",
		role: "SSA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E14",
		name: "gauravShinde",
		gender: "male",
		Location: "bkc",
		role: "SSA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E15",
		name: "ajayjangid",
		gender: "male",
		Location: "bkc",
		role: "SA1",
		wantCompoff: "no",
		availableForNight: "yes",
		interestedForContinousCompoff: "no",
		group: "G3",
	},

	{
		id: "E16",
		name: "srikant",
		gender: "male",
		Location: "bcp",
		role: "SA1",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E17",
		name: "sudarshan",
		gender: "male",
		Location: "bcp",
		role: "SA1",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E18",
		name: "chirag",
		gender: "male",
		Location: "bcp",
		role: "SA1",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E19",
		name: "abhishekMehta",
		gender: "male",
		Location: "bkc",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E20",
		name: "kavin",
		gender: "male",
		Location: "bcp",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
];
