const empList = [
	{
		id: "E1",
		name: "gita",
		gender: "female",
		Location: "bkc",
		role: "SSA2",
		wantCompoff: "no",
		availableForNight: "no",
		interestedForContinousCompoff: "no",
		group: "G1",
	},
	{
		id: "E2",
		name: "savitha",
		gender: "female",
		Location: "bcp",
		role: "SSA2",
		wantCompoff: "yes",
		availableForNight: "no",
		interestedForContinousCompoff: "yes",
		group: "G1",
	},
	{
		id: "E3",
		name: "janhvi",
		gender: "female",
		Location: "bkc",
		role: "SA1",
		wantCompoff: "yes",
		availableForNight: "no",
		interestedForContinousCompoff: "yes",
		group: "G1",
	},
	{
		id: "E4",
		name: "christina",
		gender: "female",
		Location: "bkc",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "no",
		interestedForContinousCompoff: "yes",
		group: "G1",
	},
	{
		id: "E5",
		name: "vikas",
		gender: "male",
		Location: "bkc",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "no",
		interestedForContinousCompoff: "yes",
		group: "G2",
	},
	{
		id: "E6",
		name: "prajakta",
		gender: "female",
		Location: "bkc",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "no",
		interestedForContinousCompoff: "yes",
		group: "G2",
	},
	{
		id: "E7",
		name: "vaishali",
		gender: "female",
		Location: "bkc",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "no",
		interestedForContinousCompoff: "yes",
		group: "G2",
	},
	{
		id: "E8",
		name: "arushina",
		gender: "female",
		Location: "bkc",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "no",
		interestedForContinousCompoff: "yes",
		group: "G2",
	},
	{
		id: "E9",
		name: "sarvesh",
		gender: "male",
		Location: "bkc",
		role: "LEAD1",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E10",
		name: "prabhakr",
		gender: "male",
		Location: "bcp",
		role: "LEAD2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E11",
		name: "balachander",
		gender: "male",
		Location: "bcp",
		role: "LEAD3",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E12",
		name: "santosh",
		gender: "male",
		Location: "bkc",
		role: "SSA1",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E13",
		name: "shubhamKadam",
		gender: "male",
		Location: "bkc",
		role: "SSA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E14",
		name: "gauravShinde",
		gender: "male",
		Location: "bkc",
		role: "SSA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E15",
		name: "ajayjangid",
		gender: "male",
		Location: "bkc",
		role: "SA1",
		wantCompoff: "no",
		availableForNight: "yes",
		interestedForContinousCompoff: "no",
		group: "G3",
	},

	{
		id: "E16",
		name: "srikant",
		gender: "male",
		Location: "bcp",
		role: "SA1",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E17",
		name: "sudarshan",
		gender: "male",
		Location: "bcp",
		role: "SA1",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E18",
		name: "chirag",
		gender: "male",
		Location: "bcp",
		role: "SA1",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E19",
		name: "abhishekMehta",
		gender: "male",
		Location: "bkc",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E20",
		name: "kavin",
		gender: "male",
		Location: "bcp",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E21",
		name: "shailender",
		gender: "male",
		Location: "bcp",
		role: "SA2",
		wantCompoff: "no",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G4",
	},
	{
		id: "E22",
		name: "rahul",
		gender: "male",
		Location: "bkc",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G4",
	},
	{
		id: "E23",
		name: "harsh",
		gender: "male",
		Location: "bkc",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G4",
	},
	{
		id: "E24",
		name: "sachin",
		gender: "male",
		Location: "bkc",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G4",
	},
	{
		id: "E25",
		name: "somesh",
		gender: "male",
		Location: "bcp",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G4",
	},
	{
		id: "E26",
		name: "gauravRathva",
		gender: "male",
		Location: "bkc",
		role: "SA2",
		wantCompoff: "no",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G4",
	},
	{
		id: "E27",
		name: "vivekPal",
		gender: "male",
		Location: "bkc",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E28",
		name: "krishnaReddy",
		gender: "male",
		Location: "bcp",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E29",
		name: "mankal",
		gender: "male",
		Location: "bcp",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E30",
		name: "anshul",
		gender: "male",
		Location: "bcp",
		role: "SA2",
		wantCompoff: "no",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E31",
		name: "amarnath",
		gender: "male",
		Location: "bcp",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E32",
		name: "praneeth",
		gender: "male",
		Location: "bcp",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G3",
	},
	{
		id: "E33",
		name: "praveen",
		gender: "male",
		Location: "bcp",
		role: "LEAD1",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G5",
	},
	{
		id: "E34",
		name: "abhishek",
		gender: "male",
		Location: "bkc",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G5",
	},
	{
		id: "E35",
		name: "aniket",
		gender: "male",
		Location: "bkc",
		role: "SSA1",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G5",
	},
	{
		id: "E36",
		name: "akshay",
		gender: "male",
		Location: "bkc",
		role: "SSA2",
		wantCompoff: "no",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G5",
	},
	{
		id: "E37",
		name: "mohanBhor",
		gender: "male",
		Location: "bkc",
		role: "SA1",
		wantCompoff: "no",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G5",
	},
	{
		id: "E38",
		name: "pratik",
		gender: "male",
		Location: "bcp",
		role: "SA1",
		wantCompoff: "no",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G5",
	},
	{
		id: "E39",
		name: "aravinth",
		gender: "male",
		Location: "bcp",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G5",
	},
	{
		id: "E40",
		name: "arasan",
		gender: "male",
		Location: "bcp",
		role: "SA2",
		wantCompoff: "yes",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G5",
	},
	{
		id: "E41",
		name: "susant",
		gender: "male",
		Location: "bcp",
		role: "SA2",
		wantCompoff: "no",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G5",
	},
	{
		id: "E42",
		name: "ajayv",
		gender: "male",
		Location: "bcp",
		role: "SA2",
		wantCompoff: "no",
		availableForNight: "yes",
		interestedForContinousCompoff: "yes",
		group: "G5",
	},
];

export { empList };
